title: 《.NET Core 底层入门》
logo: /assets/img/logo.jpg
description: 《.NET Core 底层入门》是一本详细介绍 .NET Core 中异常处理、多线程、GC、JIT 实现原理的书籍。
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
